export const ErrorCode = {
  NOT_GIT_REPOSITORY: "NOT_GIT_REPOSITORY",
  NOT_INITIALIZED: "NOT_INITIALIZED",
  WORKTREE_NOT_FOUND: "WORKTREE_NOT_FOUND",
  BRANCH_EXISTS: "BRANCH_EXISTS",
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  CANNOT_REMOVE_MAIN: "CANNOT_REMOVE_MAIN",
  WORKTREE_LOCKED: "WORKTREE_LOCKED",
  GH_NOT_AVAILABLE: "GH_NOT_AVAILABLE",
  INSIDE_WORKTREE: "INSIDE_WORKTREE",
  NOT_INSIDE_WORKTREE: "NOT_INSIDE_WORKTREE",
  EXEC_FAILED: "EXEC_FAILED",
  SYNC_FAILED: "SYNC_FAILED",
  IDENTIFIER_REQUIRED: "IDENTIFIER_REQUIRED",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
